# Generated by Django 5.2.4 on 2025-07-17 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_review', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='design_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_value', models.IntegerField()),
                ('comment', models.TextField()),
                ('design_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design_review.order')),
            ],
        ),
    ]
