# Generated by Django 5.2.4 on 2025-07-17 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_review', '0002_design_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='designreview',
            name='designOrders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dr_design_reviews', to='design_review.order'),
        ),
    ]
