# Generated by Django 5.2.4 on 2025-07-22 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design_review', '0005_rename_designorders_designreview_design_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designreview',
            old_name='design_orders',
            new_name='design_order',
        ),
    ]
