# Generated by Django 5.2.4 on 2025-07-22 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
