# Generated by Django 5.2.4 on 2025-07-22 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design_review', '0003_designreview_designorders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='design_review',
        ),
    ]
