# Generated by Django 5.2.4 on 2025-07-23 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_review', '0004_delete_design_review'),
        ('order', '__first__'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designreview',
            name='designOrders',
        ),
        migrations.AddField(
            model_name='designreview',
            name='design_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dr_design_reviews', to='order.order'),
        ),
    ]
