<<<<<<< HEAD
# Generated by Django 5.2.3 on 2025-06-26 12:00
=======
# Generated by Django 5.2.3 on 2025-06-27 10:59
>>>>>>> af3f64c53f9e112c757ad6cc5ba6edcbfb6c27e8

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('user_type', models.CharField(choices=[('Designer', 'Designer'), ('Trader', 'Trader')], default='designer', max_length=20)),
            ],
        ),
    ]
