# Generated by Django 5.2.4 on 2025-07-10 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user_type',
        ),
    ]
