# Generated by Django 5.2.4 on 2025-07-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='design_order',
            new_name='order_id',
        ),
        migrations.AddField(
            model_name='order',
            name='user_type',
            field=models.CharField(choices=[('Designer', 'Designer'), ('Trader', 'Trader')], default='Trader', max_length=20),
        ),
    ]
