# Generated by Django 5.2.3 on 2025-06-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designs',
            fields=[
                ('design_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('design_name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material_type', models.CharField(max_length=50)),
                ('design_image', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('design_size', models.CharField(max_length=20)),
            ],
        ),
    ]
