# Generated by Django 5.2.3 on 2025-07-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_alter_design_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
