# Generated by Django 5.2.3 on 2025-06-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('phone_number', models.CharField(max_length=20)),
                ('mpesa_receipt_number', models.CharField(max_length=20)),
            ],
        ),
    ]
