# Generated by Django 5.2.3 on 2025-07-01 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0002_remove_shopping_cart_trader_shopping_cart_design_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping_cart',
            name='design',
        ),
        migrations.RemoveField(
            model_name='shopping_cart',
            name='user',
        ),
    ]
