# Generated by Django 5.2.3 on 2025-07-01 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_rename_designs_design'),
        ('shopping_cart', '0003_remove_shopping_cart_design_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_cart',
            name='design',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='catalogue.design'),
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
    ]
