# Generated by Django 5.2.3 on 2025-06-26 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Design_review',
        ),
        migrations.DeleteModel(
            name='Shopping_cart',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
