# Generated by Django 5.2.4 on 2025-07-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('design_order', models.AutoField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(choices=[('designer', 'Designer'), ('trader', 'Trader')], default='trader', max_length=20)),
                ('order_date', models.DateField()),
                ('delivery_method', models.CharField(max_length=100)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_status', models.CharField(max_length=50)),
            ],
        ),
    ]
