# Generated by Django 5.2.3 on 2025-06-26 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('traders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traders.trader'),
        ),
        migrations.DeleteModel(
            name='Trader',
        ),
    ]
