# Generated by Django 5.2.3 on 2025-06-26 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_trader_delete_trader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='trader',
        ),
    ]
