# Generated by Django 5.2.3 on 2025-06-27 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_trader'),
        ('traders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='trader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='traders.trader'),
        ),
    ]
