# Generated by Django 5.2.3 on 2025-06-27 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_trader'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='trader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
    ]
