# Generated by Django 5.2.3 on 2025-06-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_trader'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_type',
            field=models.CharField(choices=[('designer', 'Designer'), ('customer', 'Customer')], default='designer', max_length=20),
        ),
    ]
