# Generated by Django 5.2.3 on 2025-07-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='trader',
        ),
        migrations.AlterField(
            model_name='order',
            name='user_type',
            field=models.CharField(choices=[('designer', 'Designer'), ('trader', 'Trader')], default='trader', max_length=20),
        ),
    ]
